/**
 * @file ui_strings.h
 * @brief 产品 UI 中文文案
 *
 * 注意：字体使用 LVGL 官方思源黑体简体 CJK 子集，
 * 部分罕见字可能缺失（显示为方框），首版接受此限制。
 */

#pragma once

/* 底部导航 */
#define UI_STR_HOME    "首页"
#define UI_STR_CHAT    "聊天"
#define UI_STR_MUSIC   "音乐"
#define UI_STR_SETTINGS "设置"

/* 首页 */
#define UI_STR_STATUS_BAR   "奶片助手"
#define UI_STR_TIME_TITLE   "时间"
#define UI_STR_TIME_SYNC    "待同步"
#define UI_STR_TIME_SYNCED  "已同步"
#define UI_STR_TIME_WAIT    "等待时间同步"
#define UI_STR_TIME_HINT    "系统时钟"
#define UI_STR_TIME_PLACE   "--:--"
#define UI_STR_POWER_TITLE  "电源"
#define UI_STR_POWER_CHG    "充电中"
#define UI_STR_POWER_FULL   "已充满"
#define UI_STR_POWER_IDLE   "未充电"
#define UI_STR_POWER_LIGHT  "轻载"
#define UI_STR_POWER_STABLE "状态稳定"
#define UI_STR_AUDIO_TITLE  "音频"
#define UI_STR_CONN_TITLE   "连接"
#define UI_STR_CONN_WIFI    "Wi-Fi"
#define UI_STR_CONN_UART    "串口"
#define UI_STR_CONN_WIN     "Win"
#define UI_STR_STATE_OFF    "未接入"
#define UI_STR_STATE_OK     "可用"
#define UI_STR_STATE_DISC   "未连"
#define UI_STR_STATE_ON     "已启用"
#define UI_STR_MEDIA_TITLE  "媒体"
#define UI_STR_MEDIA_NONE   "暂无音源"
#define UI_STR_HOME_SUBTITLE "设备概览 · 轻盈、清晰、随时可用"
#define UI_STR_READY         "● 系统正常"
#define UI_STR_OPEN_SETTINGS "打开设置"

/* 聊天 / 音乐 / 设置 */
#define UI_STR_CHAT_TITLE   "聊天"
#define UI_STR_CHAT_WAIT    "等待数据源"
#define UI_STR_CHAT_SUBTITLE "消息与 Windows 客户端同步"
#define UI_STR_CHAT_HINT    "连接数据源后，这里会显示最近消息"
#define UI_STR_CHAT_ENTER_LIVE2D "进入 Live2D 互动"
#define UI_STR_LIVE2D_TITLE "Live2D 互动"
#define UI_STR_LIVE2D_SUBTITLE "表情与对话随 Windows 端同步"
#define UI_STR_LIVE2D_BACK   "返回桌面"
#define UI_STR_LIVE2D_CONN   "已连接"
#define UI_STR_LIVE2D_DISC   "未连接"
#define UI_STR_LIVE2D_WAIT   "等待状态…"
#define UI_STR_LIVE2D_RECORD "按住录音"
#define UI_STR_LIVE2D_RECORDING "录音中…松开结束"

/* 语音互动（双模式） */
#define UI_STR_VOICE_ENTRY   "语音互动"
#define UI_STR_VOICE_TITLE   "语音互动"
#define UI_STR_VOICE_SUBTITLE "选择对话模式"
#define UI_STR_VOICE_MODE_LINK "连接电脑 Live2D"
#define UI_STR_VOICE_MODE_LINK_DESC "同一局域网内与 Windows 网页 Live2D 联动"
#define UI_STR_VOICE_MODE_DIRECT "独立角色对话"
#define UI_STR_VOICE_MODE_DIRECT_DESC "未连接电脑时，由设备直接调用角色 API"
#define UI_STR_VOICE_ENTER   "进入"
#define UI_STR_VOICE_HINT    "返回：切换  确认：进入  长按返回：桌面"
#define UI_STR_VOICE_LINK_OK "电脑 Live2D 已连接"
#define UI_STR_VOICE_LINK_FAIL "连接电脑失败"
#define UI_STR_VOICE_RETRY   "重试"
#define UI_STR_VOICE_SWITCH_DIRECT "切换到独立角色"
#define UI_STR_VOICE_CHECKING "正在连接…"
#define UI_STR_VOICE_DIRECT_OK "独立角色模式就绪"
#define UI_STR_VOICE_DIRECT_FAIL "独立模式不可用"
#define UI_STR_VOICE_DIRECT_NO_WIFI "未连接 Wi-Fi"
#define UI_STR_VOICE_DIRECT_NO_URL "未配置 Base URL"
#define UI_STR_VOICE_DIRECT_NO_KEY "未配置 API Key"
#define UI_STR_VOICE_DIRECT_NO_MODEL "未配置模型"
#define UI_STR_VOICE_OPEN_SETTINGS "打开设置"

/* 独立角色对话页 */
#define UI_STR_DIRECT_TITLE "独立角色对话"
#define UI_STR_DIRECT_RECORD "按住录音"
#define UI_STR_DIRECT_RECORDING "录音中…松开结束"
#define UI_STR_DIRECT_STATUS_IDLE "按住录音开始对话"
#define UI_STR_DIRECT_STATUS_STT "识别中…"
#define UI_STR_DIRECT_STATUS_LLM "思考中…"
#define UI_STR_DIRECT_STATUS_EMPTY "未识别到语音"
#define UI_STR_DIRECT_STATUS_ERR_HTTP "服务返回错误，可重试"
#define UI_STR_DIRECT_STATUS_ERR_PARSE "服务响应无法解析"
#define UI_STR_DIRECT_STATUS_ERR_CONFIG "未配置 LLM 设置"
#define UI_STR_DIRECT_STATUS_ERR_MEM "内存不足"
#define UI_STR_DIRECT_CLEAR "清空记忆"
#define UI_STR_DIRECT_ME "我"
#define UI_STR_DIRECT_ROLE "角色"
#define UI_STR_DIRECT_EMPTY_HINT "按下方按钮说话，开始独立角色对话"
#define UI_STR_MUSIC_PLACE  "暂无播放"
#define UI_STR_MUSIC_SUBTITLE "播放状态与媒体控制"
#define UI_STR_MUSIC_HINT    "预留串口、Wi-Fi 与 Windows 媒体同步"
#define UI_STR_MUSIC_CONNECT "连接设备"
#define UI_STR_MUSIC_RELEASE "释怀"
#define UI_STR_MUSIC_STOP "停止"
#define UI_STR_MUSIC_RELEASE_TITLE "关羽之歌"
#define UI_STR_MUSIC_RELEASE_HINT "点击后通过 Windows 播放网易云音乐"
#define UI_STR_MUSIC_RELEASE_OFFLINE "请先连接 Windows"
#define UI_STR_SETTINGS_DISP "显示"
#define UI_STR_SETTINGS_ROT "方向"
#define UI_STR_SETTINGS_TOUCH "触摸"
#define UI_STR_SETTINGS_BL  "背光"
#define UI_STR_SETTINGS_DEV "设备"
#define UI_STR_SETTINGS_FW  "固件"
#define UI_STR_SETTINGS_SUBTITLE "设备显示、触摸与连接状态"
#define UI_STR_SETTINGS_DISPLAY "显示与交互"
#define UI_STR_SETTINGS_DEVICE "设备信息"
#define UI_STR_SETTINGS_SYNC_HINT "预留 Wi-Fi、串口与 Windows 客户端同步接口"
#define UI_STR_SETTINGS_NET "网络与配网"
#define UI_STR_SETTINGS_NET_SSID "Wi-Fi"
#define UI_STR_SETTINGS_NET_TCP "TCP"
#define UI_STR_SETTINGS_NET_PROVISION "开始配网"
#define UI_STR_SETTINGS_NET_PROVISIONING "配网中"
#define UI_STR_SETTINGS_NET_AP_NAME "热点 SuperMilkCard"
#define UI_STR_SETTINGS_NET_AP_HINT "无密码开放热点，打开 http://192.168.4.1 配网"
#define UI_STR_SETTINGS_NET_LAN_IP "局域网地址"
#define UI_STR_SETTINGS_NET_LAN_DISC "未连接"
#define UI_STR_SETTINGS_NET_PORTAL "配置网页"
#define UI_STR_SETTINGS_NET_PORTAL_AP "开启配网后访问 http://192.168.4.1/"
#define UI_STR_UNKNOWN "未知设备"

/* 测试 */
#define UI_STR_TEST_TAP     "点击 %d 次"
